project:
  type: website
  output-dir: docs
  render:
    - "**/*.qmd"
  preview:
    port: 4212

website:
  title: Metill
  description: Notum gögn til að upplýsa, ekki sannfæra.
  site-url: https://metill.is
  favicon: "favicon/favicon-32x32.png"

  navbar:
    background: light
    foreground: dark
    title: "Metill"
    pinned: true
    left:
      - text: "Hagvísar"
        href: hagvisar/index.qmd
      - text: "Íþróttir"
        href: ithrottir/index.qmd
      - text: "Verkfæri"
        href: verkfaeri/index.qmd
      - text: "Kosningar"
        href: https://kosningar.metill.is
        target: _blank
      - text: "Um Metil"
        href: um/index.qmd
    search: true

  page-footer:
    left: "© 2025 Metill"
    center:
      - text: "Um Metil"
        href: um/index.qmd
    background: light
    border: true

  open-graph: true
  twitter-card:
    creator: "@bggjonsson"
    card-style: summary_large_image
    site: "@bggjonsson"
    title: "Metill"
    description: "Notum gögn til að upplýsa, ekki sannfæra."
  google-analytics: "G-J28QQV8PN9"

format:
  html:
    back-to-top: true

editor: source
theme: [flatly, theme.scss]
css: style.css
execute:
  freeze: auto
  echo: false
  warning: false
